export { ClockWidget } from './ClockWidget'
export { CalendarWidget } from './CalendarWidget'
export { NotesWidget } from './NotesWidget'
export { SystemInfoWidget } from './SystemInfoWidget'
export { QuickActionsWidget } from './QuickActionsWidget'
export { RecentFilesWidget } from './RecentFilesWidget'
export { TasksWidget } from './TasksWidget'
