use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        habits, notifications, pomodoro, preferences, quick_pane, recovery, tasks,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Existing commands
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        // Tasks
        tasks::get_tasks,
        tasks::get_subtasks,
        tasks::get_tasks_today,
        tasks::create_task,
        tasks::update_task,
        tasks::delete_task,
        tasks::toggle_task_complete,
        tasks::create_subtask,
        tasks::toggle_subtask,
        tasks::delete_subtask,
        // Pomodoro
        pomodoro::save_pomodoro_session,
        pomodoro::get_today_sessions,
        pomodoro::get_pomodoro_settings,
        pomodoro::save_pomodoro_settings,
        // Habits
        habits::get_habits,
        habits::create_habit,
        habits::update_habit,
        habits::archive_habit,
        habits::delete_habit,
        habits::toggle_habit_log,
        habits::get_habit_logs_range,
        habits::get_habit_logs_for_date,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
